name: flutter_openwrap_event_handler_gam
description: Dart package for supporting OpenWrap SDK's GAM header bidding.
version: 3.0.0
repository: https://github.com/PubMatic/flutter-openwrap-event-handler-gam
homepage: https://help.pubmatic.com/openwrap/docs/about-openwrap-sdk-flutter-plugin

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.6"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.0.0
  meta: ^1.10.0
  flutter_openwrap_sdk:
    version: ^2.0.0


dev_dependencies:
  lints: ^2.0.0
  test: <1.24.4
